import type { Game, Localized } from "./types";

const L = (nl: string, en: string): Localized => ({ nl, en, de: en, fr: en });

function game(partial: Game): Game {
  return partial;
}

export const GAME_LIBRARY: Game[] = [
  game({
    id: "cone-catch",
    slug: "cone-catch",
    station: 1,
    name: L("Cone Catch", "Cone Catch"),
    shortName: L("Cone Catch", "Cone Catch"),
    tagline: L("Vang. Stapel. Scoor.", "Catch. Stack. Score."),
    mission: L(
      "Vang zoveel mogelijk pionnen uit de lucht en stapel ze in jullie zone voordat de tijd om is.",
      "Catch as many flying cones as you can and stack them in your zone before time runs out.",
    ),
    howTo: [
      L("Stel op in jullie vangzone.", "Take position in your catch zone."),
      L("Vang de pionnen uit de lucht.", "Catch the cones out of the air."),
      L("Stapel ze snel in de scoretoren.", "Stack them fast in the score tower."),
    ],
    rules: [
      L("Alleen vangen met handen, niet met kleding.", "Catch with hands only, not with clothing."),
      L("Blijf in jullie vak.", "Stay inside your lane."),
    ],
    noGo: [
      L("Pionnen van andere teams afpakken", "Stealing another team's cones"),
      L("De werper hinderen", "Blocking the thrower"),
    ],
    tip: L("Roep elkaars naam. Chaos kost punten.", "Call names. Chaos costs points."),
    players: { min: 4, max: 8 },
    durationMin: 6,
    winCondition: L("MEESTE PIONNEN WINT", "MOST CONES WINS"),
    scoreMethod: "points",
    materials: L("Pionnen, scoretorens, vlaggen", "Cones, score towers, flags"),
    safety: L("Niet duiken naar pionnen op harde ondergrond.", "No diving for cones on hard ground."),
    image: "/media/game-cone-catch.jpg",
    videoDuration: "00:28",
  }),
  game({
    id: "optical-delusion",
    slug: "optical-delusion",
    station: 2,
    name: L("Optical Delusion", "Optical Delusion"),
    shortName: L("Optical", "Optical"),
    tagline: L("Jullie ogen liegen.", "Your eyes will lie."),
    mission: L(
      "Los de visuele puzzels op het strand op. Het eerste team met de juiste code wint.",
      "Solve the visual puzzles on the sand. First team with the right code wins.",
    ),
    howTo: [
      L("Bekijk het bord vanaf de markering.", "View the board from the mark."),
      L("Overleg. Eén antwoord per ronde.", "Talk it out. One answer per round."),
      L("Lever de code in bij de official.", "Hand the code to the official."),
    ],
    rules: [
      L("Niet voorbij de lijn lopen.", "Do not cross the line."),
      L("Geen foto's van het antwoordbord.", "No photos of the answer board."),
    ],
    noGo: [L("Het bord aanraken", "Touching the board"), L("Antwoorden schreeuwen naar andere teams", "Shouting answers to other teams")],
    tip: L("Stap opzij. De hoek verandert het plaatje.", "Step aside. The angle changes the picture."),
    players: { min: 4, max: 8 },
    durationMin: 7,
    winCondition: L("SNELSTE JUISTE CODE WINT", "FASTEST CORRECT CODE WINS"),
    scoreMethod: "time",
    materials: L("Illusion boards, codekaarten", "Illusion boards, code cards"),
    safety: L("Niet rennen tussen de panelen.", "Do not run between the panels."),
    image: "/media/game-optical.jpg",
    videoDuration: "00:32",
  }),
  game({
    id: "tug-battle",
    slug: "tug-battle",
    station: 3,
    name: L("Beach Tug Battle", "Beach Tug Battle"),
    shortName: L("Tug Battle", "Tug Battle"),
    tagline: L("Zand. Touw. Trots.", "Sand. Rope. Pride."),
    mission: L(
      "Trek het andere land over de middenlijn. Drie manchettes, beste van drie.",
      "Pull the other country over the centre line. Best of three.",
    ),
    howTo: [
      L("Pak het touw op jullie merkteken.", "Take the rope at your mark."),
      L("Wacht op het GO-signaal.", "Wait for the GO signal."),
      L("Trek als één machine.", "Pull as one machine."),
    ],
    rules: [
      L("Handen blijven op het touw.", "Hands stay on the rope."),
      L("Niet knopen of wikkelen om het lichaam.", "No wrapping the rope around the body."),
    ],
    noGo: [L("Zitten of liggen voor GO", "Sitting or lying before GO"), L("Het touw loslaten midden in een trek", "Letting go mid-pull")],
    tip: L("Lage voeten. Korte rukken werken beter dan wild trekken.", "Low feet. Short pulses beat wild pulling."),
    players: { min: 6, max: 8 },
    durationMin: 8,
    winCondition: L("BEST OF THREE", "BEST OF THREE"),
    scoreMethod: "head_to_head",
    materials: L("Olympic tug rope, middenvlag", "Olympic tug rope, centre flag"),
    safety: L("Handschoenen aan. Geen ringen.", "Gloves on. No rings."),
    image: "/media/game-tug.jpg",
    videoDuration: "00:26",
  }),
  game({
    id: "balance-masters",
    slug: "balance-masters",
    station: 4,
    name: L("Balance Masters", "Balance Masters"),
    shortName: L("Balance", "Balance"),
    tagline: L("Stilstand is ook een sport.", "Stillness is a sport."),
    mission: L(
      "Breng het team over de balken zonder de zandmat te raken. Tijd telt.",
      "Get the whole team across the beams without touching the sand mat. Time counts.",
    ),
    howTo: [
      L("Eén voor één het parcours op.", "Enter the course one by one."),
      L("Help elkaar in evenwicht.", "Help each other balance."),
      L("Iedereen moet finishen.", "Everyone must finish."),
    ],
    rules: [
      L("Bij een val: terug naar de laatste checkpoint.", "If you fall: back to the last checkpoint."),
      L("Niet rennen op de balken.", "No running on the beams."),
    ],
    noGo: [L("De balk verplaatsen", "Moving the beam"), L("Over het zand afsnijden", "Cutting across the sand")],
    tip: L("Kijk naar de horizon, niet naar je voeten.", "Look at the horizon, not your feet."),
    players: { min: 4, max: 8 },
    durationMin: 8,
    winCondition: L("SNELSTE SCHOON PARCOURS WINT", "FASTEST CLEAN RUN WINS"),
    scoreMethod: "time",
    materials: L("Balken, platforms, checkpoints", "Beams, platforms, checkpoints"),
    safety: L("Spotters blijven langs de zijkant.", "Spotters stay along the side."),
    image: "/media/game-balance.jpg",
    videoDuration: "00:30",
  }),
  game({
    id: "tactic-tac-toe",
    slug: "tactic-tac-toe",
    station: 5,
    name: L("Tactic Tac Toe", "Tactic Tac Toe"),
    shortName: L("Tactic", "Tactic"),
    tagline: L("Denken met je benen.", "Think with your legs."),
    mission: L(
      "Verover drie op een rij op het reuzenbord. Elk vak kost een sprint.",
      "Take three in a row on the giant board. Every square costs a sprint.",
    ),
    howTo: [
      L("Sprint naar een vak.", "Sprint to a square."),
      L("Plaats jullie landvlag.", "Place your country flag."),
      L("Blokkeer de tegenstander.", "Block the opponent."),
    ],
    rules: [L("Eén speler per beurt.", "One player per turn."), L("Vlag mag niet meer verplaatst.", "A placed flag cannot move.")],
    noGo: [L("Twee vlaggen tegelijk", "Placing two flags at once"), L("Het bord blokkeren", "Blocking the board")],
    tip: L("Eerst het midden. Daarna de hoeken.", "Take centre first. Then the corners."),
    players: { min: 4, max: 6 },
    durationMin: 6,
    winCondition: L("EERSTE DRIE-OP-RIJ WINT", "FIRST THREE-IN-A-ROW WINS"),
    scoreMethod: "head_to_head",
    materials: L("Reuzenbord, landvlaggen", "Giant board, country flags"),
    safety: L("Niet glijden in het zand bij de sprint.", "Do not slide into the sand on the sprint."),
    image: "/media/zeskamp.webp",
    videoDuration: "00:24",
  }),
  game({
    id: "giant-darts",
    slug: "giant-darts",
    station: 6,
    name: L("Giant Darts", "Giant Darts"),
    shortName: L("Darts", "Darts"),
    tagline: L("Groot bord. Grote zenuwen.", "Big board. Bigger nerves."),
    mission: L(
      "Gooi de reuzenpijlen op het strandbord. Hoogste score na zes beurten wint.",
      "Throw the giant darts at the beach board. Highest score after six rounds wins.",
    ),
    howTo: [
      L("Iedereen gooit om de beurt.", "Everyone throws in turn."),
      L("Voeten achter de lijn.", "Feet behind the line."),
      L("Tel hardop.", "Count out loud."),
    ],
    rules: [L("Pijl mag de grond niet raken voor de worp.", "The dart may not touch the ground before the throw."), L("Niet over de lijn stappen.", "Do not step over the line.")],
    noGo: [L("Rennen tijdens een worp", "Running during a throw"), L("Het bord vasthouden", "Holding the board")],
    tip: L("Niet harder. Rustiger mikken scoort meer.", "Don't throw harder. Calmer aim scores more."),
    players: { min: 4, max: 8 },
    durationMin: 8,
    winCondition: L("HOOGSTE SCORE WINT", "HIGHEST SCORE WINS"),
    scoreMethod: "points",
    materials: L("Giant darts, strandbord", "Giant darts, beach board"),
    safety: L("Alleen gooien na vrijgave van de official.", "Throw only after the official clears."),
    image: "/media/expedition.webp",
    videoDuration: "00:27",
  }),
  game({
    id: "olympic-crane",
    slug: "olympic-crane",
    station: 7,
    name: L("Olympic Crane", "Olympic Crane"),
    shortName: L("Crane", "Crane"),
    tagline: L("Zes mensen. Eén machine.", "Six people. One machine."),
    mission: L(
      "Werk samen om met zes touwen de centrale grijper te bedienen. Verplaats zoveel mogelijk objecten naar de scorezone.",
      "Work together to operate the central grabber with six ropes. Move as many objects as you can into the score zone.",
    ),
    howTo: [
      L("Iedere speler pakt één touw.", "Each player takes one rope."),
      L("Bedien samen de grijper.", "Operate the grabber together."),
      L("Pak een object op.", "Pick up an object."),
      L("Plaats het in de juiste scorezone.", "Place it in the correct score zone."),
    ],
    rules: [
      L("Iedereen blijft achter eigen lijn", "Everyone stays behind their own line"),
      L("Object mag niet met handen worden aangeraakt", "Objects may not be touched by hand"),
      L("Alleen toegewezen touw gebruiken", "Use only your assigned rope"),
    ],
    noGo: [L("Materiaal vastpakken", "Grabbing the equipment"), L("Andere teams hinderen", "Interfering with other teams")],
    tip: L("Rustig bewegen werkt vaak sneller dan trekken.", "Moving calmly is often faster than pulling."),
    players: { min: 6, max: 6 },
    durationMin: 8,
    winCondition: L("MEESTE PUNTEN WINT", "MOST POINTS WINS"),
    scoreMethod: "head_to_head",
    materials: L("Centrale grijper, zes touwen, score-objecten", "Central grabber, six ropes, score objects"),
    safety: L("Niet over de lijn stappen. Touwen niet om polsen wikkelen.", "Do not cross the line. Do not wrap ropes around wrists."),
    image: "/media/game-olympic-crane.jpg",
    videoDuration: "00:42",
  }),
  game({
    id: "gold-rush",
    slug: "gold-rush",
    station: 8,
    name: L("Gold Rush", "Gold Rush"),
    shortName: L("Gold Rush", "Gold Rush"),
    tagline: L("Dubbele punten. Alles kan kantelen.", "Double points. Everything can flip."),
    mission: L(
      "Verzamel gouden tokens in het zand. Elk token telt dubbel tijdens het Golden Event.",
      "Collect gold tokens from the sand. Every token counts double during the Golden Event.",
    ),
    howTo: [
      L("Wacht op het gouden signaal.", "Wait for the golden signal."),
      L("Zoek tokens in jullie sector.", "Hunt tokens in your sector."),
      L("Lever in bij de kist.", "Deliver them to the chest."),
    ],
    rules: [L("Alleen in jullie sector graven.", "Search only in your sector."), L("Tokens zichtbaar houden.", "Keep tokens visible.")],
    noGo: [L("Tokens begraven voor anderen", "Burying tokens for others"), L("De kist verplaatsen", "Moving the chest")],
    tip: L("Splits: twee zoekers, twee lopers.", "Split: two hunters, two runners."),
    players: { min: 4, max: 8 },
    durationMin: 8,
    winCondition: L("MEESTE GOUDEN TOKENS WINT", "MOST GOLD TOKENS WINS"),
    scoreMethod: "points",
    materials: L("Gouden tokens, teamkisten", "Gold tokens, team chests"),
    safety: L("Niet graven bij de vlaggenlijnen.", "Do not dig near flag lines."),
    image: "/media/olympic-flame.jpg",
    videoDuration: "00:35",
  }),
  game({
    id: "water-works",
    slug: "water-works",
    station: 9,
    name: L("Water Works", "Water Works"),
    shortName: L("Water Works", "Water Works"),
    tagline: L("Lekker nat. Geen excuses.", "Soaked. No excuses."),
    mission: L(
      "Vervoer water over het parcours zonder te morsen. Vul jullie Olympic vat.",
      "Carry water across the course without spilling. Fill your Olympic barrel.",
    ),
    howTo: [
      L("Vul de emmer aan zee.", "Fill the bucket at the sea."),
      L("Breng hem over het parcours.", "Carry it across the course."),
      L("Leeg in het vat.", "Empty it into the barrel."),
    ],
    rules: [L("Emmer mag niet op de grond rusten onderweg.", "The bucket may not rest on the ground in transit."), L("Iedereen moet minstens één run doen.", "Everyone must do at least one run.")],
    noGo: [L("Water uit andere vaten scheppen", "Scooping from other barrels"), L("Het parcours afsnijden", "Cutting the course")],
    tip: L("Langzamer lopen = meer water = meer punten.", "Walk slower = more water = more points."),
    players: { min: 4, max: 8 },
    durationMin: 8,
    winCondition: L("HOOGSTE WATERLIJN WINT", "HIGHEST WATERLINE WINS"),
    scoreMethod: "points",
    materials: L("Emmers, vaten, parcours", "Buckets, barrels, course"),
    safety: L("Niet rennen op natte platen.", "Do not run on wet boards."),
    image: "/media/game-water.jpg",
    videoDuration: "00:29",
  }),
  game({
    id: "target-attack",
    slug: "target-attack",
    station: 10,
    name: L("Target Attack", "Target Attack"),
    shortName: L("Target", "Target"),
    tagline: L("Mik. Adem. Raak.", "Aim. Breathe. Hit."),
    mission: L(
      "Raak de landendoelen met de beachballs. Moeilijke doelen geven meer punten.",
      "Hit the country targets with beachballs. Tougher targets score more.",
    ),
    howTo: [
      L("Pak één ball per beurt.", "Take one ball per turn."),
      L("Mik vanaf de lijn.", "Aim from the line."),
      L("Wissel na elke worp.", "Rotate after every throw."),
    ],
    rules: [L("Voeten achter de lijn.", "Feet behind the line."), L("Niet op het doel inrennen.", "Do not charge the target.")],
    noGo: [L("Doelen vasthouden", "Holding the targets"), L("Balls van anderen gebruiken", "Using another team's balls")],
    tip: L("Eerst de makkelijke punten. Daarna het goud.", "Bank the easy points. Then go for gold."),
    players: { min: 4, max: 8 },
    durationMin: 7,
    winCondition: L("HOOGSTE SCORE WINT", "HIGHEST SCORE WINS"),
    scoreMethod: "points",
    materials: L("Targets, beachballs", "Targets, beachballs"),
    safety: L("Niet gooien als iemand voor het doel staat.", "Do not throw while someone is in front of the target."),
    image: "/media/escape.webp",
    videoDuration: "00:25",
  }),
  game({
    id: "olympic-code",
    slug: "olympic-code",
    station: 11,
    name: L("Olympic Code", "Olympic Code"),
    shortName: L("Code", "Code"),
    tagline: L("Brein onder druk.", "Brains under pressure."),
    mission: L(
      "Kraak de strandcode met aanwijzingen verspreid over het station. Snelheid + juistheid.",
      "Crack the beach code with clues spread across the station. Speed plus accuracy.",
    ),
    howTo: [
      L("Verdeel de clues over het team.", "Split the clues across the team."),
      L("Breng de letters samen.", "Bring the letters together."),
      L("Voer de code in bij de official.", "Submit the code to the official."),
    ],
    rules: [L("Clues mogen niet meegenomen worden.", "Clues may not be taken away."), L("Eén poging per twee minuten.", "One attempt every two minutes.")],
    noGo: [L("Clues van andere stations lezen", "Reading clues from other stations"), L("De official om hints vragen", "Asking the official for hints")],
    tip: L("Eén runner, één decoder. Niet iedereen rennen.", "One runner, one decoder. Don't all sprint."),
    players: { min: 4, max: 8 },
    durationMin: 8,
    winCondition: L("SNELSTE JUISTE CODE WINT", "FASTEST CORRECT CODE WINS"),
    scoreMethod: "time",
    materials: L("Codekisten, aanwijzingen", "Code chests, clues"),
    safety: L("Niet in kisten duiken met het hoofd.", "Do not dive head-first into chests."),
    image: "/media/robinson.webp",
    videoDuration: "00:33",
  }),
  game({
    id: "surf-shuffle",
    slug: "surf-shuffle",
    station: 12,
    name: L("Surf Shuffle", "Surf Shuffle"),
    shortName: L("Shuffle", "Shuffle"),
    tagline: L("Timing op het zand.", "Timing on the sand."),
    mission: L(
      "Schuif de surf-pucks over het strandcourt. Dichtste bij de flame-lijn wint.",
      "Slide the surf pucks across the beach court. Closest to the flame line wins.",
    ),
    howTo: [
      L("Eén puck per speler.", "One puck per player."),
      L("Schuif, gooi niet.", "Slide, don't throw."),
      L("Meet na de laatste puck.", "Measure after the last puck."),
    ],
    rules: [L("Puck blijft op het zand.", "The puck stays on the sand."), L("Geen duw na loslaten.", "No extra push after release.")],
    noGo: [L("Het court vegen tijdens de beurt", "Sweeping the court mid-turn"), L("Pucks van anderen verzetten", "Moving another team's pucks")],
    tip: L("Korte sliding. Het zand remt harder dan je denkt.", "Short slides. Sand brakes harder than you think."),
    players: { min: 4, max: 8 },
    durationMin: 7,
    winCondition: L("DICHTSTE BIJ DE FLAME WINT", "CLOSEST TO THE FLAME WINS"),
    scoreMethod: "points",
    materials: L("Surf pucks, courtlijnen", "Surf pucks, court lines"),
    safety: L("Niet op de pucks staan.", "Do not stand on the pucks."),
    image: "/media/volley.webp",
    videoDuration: "00:22",
  }),
  game({
    id: "olympic-relay",
    slug: "olympic-relay",
    station: 0,
    name: L("The Olympic Relay", "The Olympic Relay"),
    shortName: L("Relay", "Relay"),
    tagline: L("Alle landen. Eén laatste kans.", "All countries. One last chance."),
    mission: L(
      "De finale-estafette rond de Central Arena. Ieder land, één vlam, volle gas.",
      "The final relay around the Central Arena. Every country, one flame, full send.",
    ),
    howTo: [
      L("Meld je bij de Central Arena.", "Report to the Central Arena."),
      L("Neem de vlamstok over in de wisselzone.", "Take the flame baton in the exchange zone."),
      L("Finish voor de cauldron.", "Finish in front of the cauldron."),
    ],
    rules: [L("Wissel alleen in de zone.", "Exchange only inside the zone."), L("De vlamstok mag de grond niet raken.", "The flame baton may not touch the ground.")],
    noGo: [L("Afkorten over de arena", "Cutting through the arena"), L("Een andere loper tegenhouden", "Blocking another runner")],
    tip: L("De wissel wint finales. Oefen die drie seconden.", "The handoff wins finals. Rehearse those three seconds."),
    players: { min: 6, max: 8 },
    durationMin: 10,
    winCondition: L("EERSTE OVER DE STREEP WINT", "FIRST ACROSS THE LINE WINS"),
    scoreMethod: "time",
    materials: L("Flame batons, wisselzones", "Flame batons, exchange zones"),
    safety: L("Geen spikes. Blijf in je baan.", "No spikes. Stay in your lane."),
    image: "/media/medal-ceremony.jpg",
    videoDuration: "00:38",
  }),
];

export function gameById(id: string) {
  return GAME_LIBRARY.find((g) => g.id === id);
}

export function gameBySlug(slug: string) {
  return GAME_LIBRARY.find((g) => g.slug === slug);
}

export function gameByStation(station: number) {
  return GAME_LIBRARY.find((g) => g.station === station);
}
